version: "3.7"
services:
  dunehost:
    hostname: "dunehost"
    privileged: true
    image: dune:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Use network -> host if you feel like it.
      - 8080:8080
